
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password" : "admin"
}

###
POST http://localhost:3000/plan
Content-Type: application/json
Authorization: 1ca3bb8d-47f4-4c7f-8310-533df4c42cd9

{
    "title": "hell",
    "description" : "sorme"
}

###
GET http://localhost:3000/plan/2

