
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password" : "admin"
}

###
POST http://localhost:3000/plan
Content-Type: application/json
Authorization: 6f158c23-9cbe-4ff8-b52f-f1a8c12ac486

{
    "title": "hell",
    "description" : "sorme",
    "deadLine" : "2025-03-02"
}

###
GET http://localhost:3000/plan/1

